sudo: required
services:
  - docker
language: bash
env:
  global:
  - secure: "nw9C6gFPx6eWBexivPgyxZpGWRt5Ules6ISojwZ1+xOa2JYcJqMpN0nZTmU/qNp32jMCT5szcIROH++lJ9Tb7r4uCGyyVos2OzdmfFqTqfNo0a6nXZt+fOrq9vQjfd11XQkKqKEAsZ1bH8E0QjdHWLyp+p+mOoGJiwzr/Gs1hJ2d54yFWqyge/d9kD/79JhfHuMhcENmftYzmMn8hFWZ7ABspwwq6gfp+UwOGYuXVEhGX6XCc78SEBU1ba8k9yFeE9NIdeyXPbYaxbZEp2csFzMTOvPEyfTxnCjfMj+04slWP9cK0JnXG9MgZyA9loFWdGOiin4G7blcSpX7pq+4/UiKpFQl0kIBAEEV190DVkI/SKNOCFnIfTtf9QfmkbtxmEHIDElnmM2V1up/iDRiEet54w6Ht2IYdnM7wWqsznRqaVAtJQq4JZrARBUp8DqSs2egj1c14IznOAOB22v/d9LtQ2atF0mKkO+bEYh5TN+djQOCDhtTU16ZACMwRRhlxp2g1E2TB71A6Uf0nqZWDChh1iHWq6hd2LB/1OwUrNuqDuHg/ETWd4Y/LjzQHidD2zWGLihWKyFEepjleya90qOwZZx3yBjZiHGelkghwauyrm8cey5XK1clXrJ33FfEE/sv7et6daX5g5xQvKa9rs9UTN+wXItK6AlJ2p/Ht/M="
  - secure: "n0mcLZVxRmeJunRH1R0gwNIgKmXzt1B1tfVY71UuE6R3KtsZFIXsdVsN47y2fRtyFA3z1cH6uSQDhkrFii4l2OkrOE92e4eMVhd79atIAZjC0loZFxEEhDjc9nKANFpEoSSu/ZTDtea470OrkO1Gc4T/qjiQZJg3KolpGj1rPpsUJQ3zHBagC/AiRXsUclA0yQbV6BcSxRjccwen0iSIkN3VE8CRAPKVT/bIlSq+4F1XQMnjB34nKn+r9aNGdwbw6s8cyJFrI8xRVCZEAwC7BSevZSWbZfEdf5l/Ixr7N4gxJz/YMGOCthubHmS9GuHHvQBwDqvyxDzOdXr02HZv7Y62Oib/cpLtQigeHaq/fxOiY94sZPJaFCqy0zkLKgHcj21BD/r44AwmGMZiPC3VZeDRv9QqJjhaKaP63MH202oTyFgOCZdbsl7pn/h2/3woM9jH+gFlknpheIkVW7PbxYAPV0/eJxUR671ExmaAUWmDHfZlpM7+UatnDhbaFNPziFdSQSTtKtJSygfhMYDTj/B/hLMjVpXq2Chw+nW2dpvFSysaIjsWpD5U+DgJk6eZjnqR3Vm+pefquPWI1MB/qmIgr2A8CVPpHJLjwPQ16cVjjpL5nwSpemGr1FdM/UBQuchN77PzzdS5CZDXtYAywxAf4/g0LoJYLOQrRUTk9V0="
install:
  - wget https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64 -O manifest-tool
  - chmod +x manifest-tool
jobs:
  include:
    - stage: Build docker images
      env:
        - ARCH=amd64
      script:
      # Build amd64
        - docker build -t "duffbeer2000/iobroker:$ARCH" ./amd64
      # Build amd64-min
        - docker build -t "duffbeer2000/iobroker:$ARCH-min" ./amd64-min
      # Build amd64-full
        - docker build -t "duffbeer2000/iobroker:$ARCH-full" ./amd64-full
    - stage: Build docker images
      env:
        - ARCH=aarch64
      script:
      # Switch Architecture
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
      # Build aarch64
        - docker build -t "duffbeer2000/iobroker:$ARCH" ./aarch64
      # Build aarch64-min
        - docker build -t "duffbeer2000/iobroker:$ARCH-min" ./aarch64-min
      # Build aarch64-full
        - docker build -t "duffbeer2000/iobroker:$ARCH-full" ./aarch64-full
    - stage: Build docker images
      env:
        - ARCH=arm7hf
      script:
      # Switch Architecture
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
      # Build armv7hf
        - docker build -t "duffbeer2000/iobroker:$ARCH" ./armv7hf
      # Build armv7hf-min
        - docker build -t "duffbeer2000/iobroker:$ARCH-min" ./armv7hf-min
      # Build armv7hf-full
        - docker build -t "duffbeer2000/iobroker:$ARCH-full" ./armv7hf-full
      #
after_success:
# Tag and push built images
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      echo "$DOCKER_PASS" | docker login -u "$DOCKER_LOGIN" --password-stdin
      VERSION=$(cat .VERSION)
      docker tag duffbeer2000/iobroker:$ARCH duffbeer2000/iobroker:$ARCH-$VERSION
      docker push duffbeer2000/iobroker:$ARCH
      docker push duffbeer2000/iobroker:$ARCH-$VERSION
      docker tag duffbeer2000/iobroker:$ARCH-min duffbeer2000/iobroker:$ARCH-min-$VERSION
      docker push duffbeer2000/iobroker:$ARCH-min
      docker push duffbeer2000/iobroker:$ARCH-min-$VERSION
      docker tag duffbeer2000/iobroker:$ARCH-full duffbeer2000/iobroker:$ARCH-full-$VERSION
      docker push duffbeer2000/iobroker:$ARCH-full
      docker push duffbeer2000/iobroker:$ARCH-full-$VERSION
    fi
# Update repository manifest for multiarch duffbeer2000/iobroker:latest
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      ./manifest-tool --username $DOCKER_LOGIN --password $DOCKER_PASS push from-spec manifest.yml
    fi
